// Generated by CoffeeScript 1.12.7
(function() {
  var BackendConfig, BackendWatchConfig, _, webpack,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  _ = require('lodash');

  webpack = require('webpack');

  BackendConfig = require('./backend');

  module.exports = BackendWatchConfig = (function(superClass) {
    extend(BackendWatchConfig, superClass);

    function BackendWatchConfig() {
      var ref;
      BackendWatchConfig.__super__.constructor.apply(this, arguments);
      this.config.cache = true;
      this.config.debug = true;
      if (this.options.unsafeCache !== false) {
        this.config.resolve.unsafeCache = this.options.unsafeCache;
      }
      this.config.devtool = (ref = this.options.backend.devtool) != null ? ref : this.options.devtool;
    }

    return BackendWatchConfig;

  })(BackendConfig);

}).call(this);
