// Generated by CoffeeScript 1.12.7
(function() {
  var BackendBuildConfig, BackendConfig, _, webpack,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  _ = require('lodash');

  webpack = require('webpack');

  BackendConfig = require('./backend');

  module.exports = BackendBuildConfig = (function(superClass) {
    extend(BackendBuildConfig, superClass);

    function BackendBuildConfig() {
      BackendBuildConfig.__super__.constructor.apply(this, arguments);
      _.defaultsDeep(this.options, {
        backend: {
          cache: false,
          uglify: true
        }
      });
      this.config.cache = this.options.backend.cache;
      this.config.debug = false;
      this.config.devtool = 'source-map';
      if (this.options.backend.uglify) {
        this.config.plugins.push(new webpack.optimize.UglifyJsPlugin({
          compress: {
            warnings: false
          }
        }));
      }
    }

    return BackendBuildConfig;

  })(BackendConfig);

}).call(this);
